# pytest.ini
[pytest]
# Configura o Pytest para carregar as configurações do Django
DJANGO_SETTINGS_MODULE = core.settings
# Define os apps onde o Pytest deve procurar por testes
python_files = tests.py test_*.py *_tests.py
# Adiciona o diretório raiz dos apps para descoberta de testes
addopts = --reuse-db