# Generated by Django 5.2.8 on 2025-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('OUT', 'Emprestado'), ('RET', 'Devolvido'), ('OVD', 'Atrasado')], default='OUT', max_length=3),
        ),
    ]
