# Generated by Django 5.2.8 on 2025-11-18 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('book_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('page_count', models.IntegerField()),
                ('last_edition', models.DateField()),
                ('language', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('DE', 'Alemão'), ('IT', 'Italiano')], max_length=50)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Borrowed', 'Borrowed')], default='Available', max_length=10, verbose_name='Book Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
