# Generated by Django 5.2.8 on 2025-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('PT', 'Português'), ('PT-BR', 'Português (Brasil)'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('DE', 'Alemão'), ('IT', 'Italiano'), ('RU', 'Russo'), ('NL', 'Holandês'), ('SV', 'Sueco'), ('DA', 'Dinamarquês'), ('NO', 'Norueguês'), ('FI', 'Finlandês'), ('PL', 'Polaco'), ('RO', 'Romeno'), ('EL', 'Grego'), ('HU', 'Húngaro'), ('CS', 'Checo'), ('TR', 'Turco'), ('UK', 'Ucraniano'), ('ZH', 'Chinês (Mandarim)'), ('JA', 'Japonês'), ('KO', 'Coreano'), ('HI', 'Hindi'), ('AR', 'Árabe'), ('ID', 'Indonésio'), ('TH', 'Tailandês'), ('VI', 'Vietnamita'), ('HE', 'Hebraico'), ('FA', 'Persa (Farsi)'), ('ML', 'Malaiala'), ('BN', 'Bengali'), ('AF', 'Africâner'), ('SW', 'Suaíli'), ('CA', 'Catalão'), ('GA', 'Irlandês'), ('IS', 'Islandês'), ('LA', 'Latim')], max_length=50),
        ),
    ]
