# Generated by Django 5.2.8 on 2025-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FIC', 'Ficção Literária'), ('FAN', 'Fantasia'), ('SCF', 'Ficção Científica'), ('THR', 'Suspense / Thriller'), ('MYT', 'Mistério / Policial'), ('ROM', 'Romance'), ('HOR', 'Terror / Horror'), ('JUV', 'Literatura Juvenil'), ('INF', 'Literatura Infantil'), ('POE', 'Poesia'), ('HIS', 'História'), ('BIO', 'Biografia / Memórias'), ('SEL', 'Autoajuda / Desenvolvimento Pessoal'), ('FIL', 'Filosofia'), ('REL', 'Religião / Espiritualidade'), ('ART', 'Artes / Design / Fotografia'), ('CUL', 'Culinária'), ('CIJ', 'Ciências Sociais e Jurídicas'), ('CIE', 'Ciências Exatas e Naturais'), ('TEC', 'Tecnologia / Computação')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
